; PlatformIO Project Configuration File

[env:rymcu-esp32-s3-devkitc-1]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino

build_flags = 
    -I .pio/libdeps/rymcu-esp32-s3-devkitc-1/Fusion/Fusion
    -O3
    -D CORE_DEBUG_LEVEL=3
    
build_src_filter = 
    +<*> 
    -<deprecated/>
    
upload_speed = 115200
monitor_speed = 115200

board_build.flash_mode = dio

lib_deps =
    bolderflight/Bolder Flight Systems MPU9250 @ ^1.0.2
    hideakitai/ArxTypeTraits @ ^0.3.1
    hideakitai/ArduinoEigen
    https://github.com/xioTechnologies/Fusion.git#v1.2.11

lib_ldf_mode = chain+
lib_ignore = Fusion/Examples, Fusion/Python

upload_port = COM10
monitor_port = COM10